name: Build-And-Deploy-Testflight

on:
  workflow_dispatch:

jobs:
  testflight:
    name: Build and Deploy Testflight
    runs-on: macOS-latest
    strategy:
      matrix:
        ruby: ['2.7']
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Access Match Repository via SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Test Git Access
      run: git clone ${{ secrets.MATCH_GIT_REPO }}
